### ISSUE TITLE
Tika Exceptions

### ISSUE THREAD

**Issue by iklemm** [abrom/henkei#49]
I tried it with Ruby 3.2 and Java 8 and Java 17 and with a handful docx and xlsx files.

The only thing i get are a bunch of Tika expections like the following (and others...)

Any help appreciated, Thanks.

`##########################
test.docx
##########################
Exception in thread "main" org.apache.tika.exception.TikaException: Couldn't find core part
        at org.apache.tika.parser.microsoft.ooxml.OOXMLExtractorFactory.tryXSLF(OOXMLExtractorFactory.java:314)
        at org.apache.tika.parser.microsoft.ooxml.OOXMLExtractorFactory.parse(OOXMLExtractorFactory.java:199)
        at org.apache.tika.parser.microsoft.ooxml.OOXMLParser.parse(OOXMLParser.java:118)
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
        at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:203)
        at org.apache.tika.cli.TikaCLI$OutputType.process(TikaCLI.java:1071)
        at org.apache.tika.cli.TikaCLI.process(TikaCLI.java:478)
        at org.apache.tika.cli.TikaCLI.main(TikaCLI.java:259)`

**Comment by abrom** [comment]
can you share some more details about what you're actually trying to do? And with which versions (of the gem, thus Tika version) you're trying to do them?

Henkei is an exceptionally thin wrapper around Tika, and this is sounding very much like a Tika issue. You can test this yourself with something like (to read the text contents of the file):

```
java -Djava.awt.headless=true -jar <path to tika-app.jar> -t <your file path>
```

See https://tika.apache.org/3.0.0/gettingstarted.html#Using_Tika_as_a_command_line_utility

You can get the Tika App jar files from https://tika.apache.org/download.html

**Comment by iklemm** [comment]
Thank you for your answer! In the meantime i gave up figuring out whats going wrong and created my own solution. Since i only needed a tool to retrieve some metadata from office files it was not a big thing.
